# Generated by Django 5.2.1 on 2025-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('video_types', models.CharField(help_text='e.g., funny, gaming, beauty, etc.', max_length=255)),
                ('followers_count', models.PositiveIntegerField()),
                ('gets_engagement', models.BooleanField(help_text='Do your videos usually get a lot of likes and comments?')),
                ('preferred_payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('gopay', 'GoPay'), ('ovo', 'OVO'), ('dana', 'DANA'), ('linkaja', 'LinkAja')], max_length=10)),
                ('preferred_currency', models.CharField(max_length=10)),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('taxpayer_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='NPWP (Taxpayer ID)')),
            ],
        ),
    ]
