# Generated by Django 5.2.1 on 2025-05-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokprofile',
            name='gets_engagement',
            field=models.CharField(help_text='Yes or No'),
        ),
    ]
