# Generated by Django 5.2.1 on 2025-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('instagram_handle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=255, verbose_name='Modeling niche')),
                ('q2', models.TextField(verbose_name='Photoshoot preparation')),
                ('q3', models.TextField(verbose_name='Comfort with traditional attire')),
                ('q4', models.TextField(blank=True, verbose_name='Creative concepts/themes')),
                ('q5', models.TextField(blank=True, verbose_name='Preferred timeframe')),
                ('q6', models.TextField(blank=True, verbose_name='Openness to diverse locations')),
                ('q7', models.TextField(blank=True, verbose_name='Usual shoot rates')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
